# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d3e396978e3e933ae186a203e56067561472776dc401588e96baf623db26432a95786854f532e07ab2d892e690a04e3da0f1ebdc36002e520396d0ca99c6eda

test:
  secret_key_base: c07450248900c004e82dc744fcf956a2089ac90cf040d9e6e3f539eb721a0ba7e5cadfd4178378fee58f9310cf16983d24cb0d4c193cdc59840c2ef96293084e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
